require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CskillsController do

  # This should return the minimal set of attributes required to create a valid
  # Cskill. As you add validations to Cskill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CskillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cskills as @cskills" do
      cskill = Cskill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cskills).should eq([cskill])
    end
  end

  describe "GET show" do
    it "assigns the requested cskill as @cskill" do
      cskill = Cskill.create! valid_attributes
      get :show, {:id => cskill.to_param}, valid_session
      assigns(:cskill).should eq(cskill)
    end
  end

  describe "GET new" do
    it "assigns a new cskill as @cskill" do
      get :new, {}, valid_session
      assigns(:cskill).should be_a_new(Cskill)
    end
  end

  describe "GET edit" do
    it "assigns the requested cskill as @cskill" do
      cskill = Cskill.create! valid_attributes
      get :edit, {:id => cskill.to_param}, valid_session
      assigns(:cskill).should eq(cskill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cskill" do
        expect {
          post :create, {:cskill => valid_attributes}, valid_session
        }.to change(Cskill, :count).by(1)
      end

      it "assigns a newly created cskill as @cskill" do
        post :create, {:cskill => valid_attributes}, valid_session
        assigns(:cskill).should be_a(Cskill)
        assigns(:cskill).should be_persisted
      end

      it "redirects to the created cskill" do
        post :create, {:cskill => valid_attributes}, valid_session
        response.should redirect_to(Cskill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cskill as @cskill" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cskill.any_instance.stub(:save).and_return(false)
        post :create, {:cskill => {}}, valid_session
        assigns(:cskill).should be_a_new(Cskill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cskill.any_instance.stub(:save).and_return(false)
        post :create, {:cskill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cskill" do
        cskill = Cskill.create! valid_attributes
        # Assuming there are no other cskills in the database, this
        # specifies that the Cskill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cskill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cskill.to_param, :cskill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cskill as @cskill" do
        cskill = Cskill.create! valid_attributes
        put :update, {:id => cskill.to_param, :cskill => valid_attributes}, valid_session
        assigns(:cskill).should eq(cskill)
      end

      it "redirects to the cskill" do
        cskill = Cskill.create! valid_attributes
        put :update, {:id => cskill.to_param, :cskill => valid_attributes}, valid_session
        response.should redirect_to(cskill)
      end
    end

    describe "with invalid params" do
      it "assigns the cskill as @cskill" do
        cskill = Cskill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cskill.any_instance.stub(:save).and_return(false)
        put :update, {:id => cskill.to_param, :cskill => {}}, valid_session
        assigns(:cskill).should eq(cskill)
      end

      it "re-renders the 'edit' template" do
        cskill = Cskill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cskill.any_instance.stub(:save).and_return(false)
        put :update, {:id => cskill.to_param, :cskill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cskill" do
      cskill = Cskill.create! valid_attributes
      expect {
        delete :destroy, {:id => cskill.to_param}, valid_session
      }.to change(Cskill, :count).by(-1)
    end

    it "redirects to the cskills list" do
      cskill = Cskill.create! valid_attributes
      delete :destroy, {:id => cskill.to_param}, valid_session
      response.should redirect_to(cskills_url)
    end
  end

end
