require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CstrategiesController do

  # This should return the minimal set of attributes required to create a valid
  # Cstrategy. As you add validations to Cstrategy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CstrategiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all cstrategies as @cstrategies" do
      cstrategy = Cstrategy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cstrategies).should eq([cstrategy])
    end
  end

  describe "GET show" do
    it "assigns the requested cstrategy as @cstrategy" do
      cstrategy = Cstrategy.create! valid_attributes
      get :show, {:id => cstrategy.to_param}, valid_session
      assigns(:cstrategy).should eq(cstrategy)
    end
  end

  describe "GET new" do
    it "assigns a new cstrategy as @cstrategy" do
      get :new, {}, valid_session
      assigns(:cstrategy).should be_a_new(Cstrategy)
    end
  end

  describe "GET edit" do
    it "assigns the requested cstrategy as @cstrategy" do
      cstrategy = Cstrategy.create! valid_attributes
      get :edit, {:id => cstrategy.to_param}, valid_session
      assigns(:cstrategy).should eq(cstrategy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cstrategy" do
        expect {
          post :create, {:cstrategy => valid_attributes}, valid_session
        }.to change(Cstrategy, :count).by(1)
      end

      it "assigns a newly created cstrategy as @cstrategy" do
        post :create, {:cstrategy => valid_attributes}, valid_session
        assigns(:cstrategy).should be_a(Cstrategy)
        assigns(:cstrategy).should be_persisted
      end

      it "redirects to the created cstrategy" do
        post :create, {:cstrategy => valid_attributes}, valid_session
        response.should redirect_to(Cstrategy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cstrategy as @cstrategy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cstrategy.any_instance.stub(:save).and_return(false)
        post :create, {:cstrategy => {}}, valid_session
        assigns(:cstrategy).should be_a_new(Cstrategy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cstrategy.any_instance.stub(:save).and_return(false)
        post :create, {:cstrategy => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cstrategy" do
        cstrategy = Cstrategy.create! valid_attributes
        # Assuming there are no other cstrategies in the database, this
        # specifies that the Cstrategy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cstrategy.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => cstrategy.to_param, :cstrategy => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested cstrategy as @cstrategy" do
        cstrategy = Cstrategy.create! valid_attributes
        put :update, {:id => cstrategy.to_param, :cstrategy => valid_attributes}, valid_session
        assigns(:cstrategy).should eq(cstrategy)
      end

      it "redirects to the cstrategy" do
        cstrategy = Cstrategy.create! valid_attributes
        put :update, {:id => cstrategy.to_param, :cstrategy => valid_attributes}, valid_session
        response.should redirect_to(cstrategy)
      end
    end

    describe "with invalid params" do
      it "assigns the cstrategy as @cstrategy" do
        cstrategy = Cstrategy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cstrategy.any_instance.stub(:save).and_return(false)
        put :update, {:id => cstrategy.to_param, :cstrategy => {}}, valid_session
        assigns(:cstrategy).should eq(cstrategy)
      end

      it "re-renders the 'edit' template" do
        cstrategy = Cstrategy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cstrategy.any_instance.stub(:save).and_return(false)
        put :update, {:id => cstrategy.to_param, :cstrategy => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cstrategy" do
      cstrategy = Cstrategy.create! valid_attributes
      expect {
        delete :destroy, {:id => cstrategy.to_param}, valid_session
      }.to change(Cstrategy, :count).by(-1)
    end

    it "redirects to the cstrategies list" do
      cstrategy = Cstrategy.create! valid_attributes
      delete :destroy, {:id => cstrategy.to_param}, valid_session
      response.should redirect_to(cstrategies_url)
    end
  end

end
