require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LessonResourcesController do

  # This should return the minimal set of attributes required to create a valid
  # LessonResource. As you add validations to LessonResource, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LessonResourcesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lesson_resources as @lesson_resources" do
      lesson_resource = LessonResource.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lesson_resources).should eq([lesson_resource])
    end
  end

  describe "GET show" do
    it "assigns the requested lesson_resource as @lesson_resource" do
      lesson_resource = LessonResource.create! valid_attributes
      get :show, {:id => lesson_resource.to_param}, valid_session
      assigns(:lesson_resource).should eq(lesson_resource)
    end
  end

  describe "GET new" do
    it "assigns a new lesson_resource as @lesson_resource" do
      get :new, {}, valid_session
      assigns(:lesson_resource).should be_a_new(LessonResource)
    end
  end

  describe "GET edit" do
    it "assigns the requested lesson_resource as @lesson_resource" do
      lesson_resource = LessonResource.create! valid_attributes
      get :edit, {:id => lesson_resource.to_param}, valid_session
      assigns(:lesson_resource).should eq(lesson_resource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LessonResource" do
        expect {
          post :create, {:lesson_resource => valid_attributes}, valid_session
        }.to change(LessonResource, :count).by(1)
      end

      it "assigns a newly created lesson_resource as @lesson_resource" do
        post :create, {:lesson_resource => valid_attributes}, valid_session
        assigns(:lesson_resource).should be_a(LessonResource)
        assigns(:lesson_resource).should be_persisted
      end

      it "redirects to the created lesson_resource" do
        post :create, {:lesson_resource => valid_attributes}, valid_session
        response.should redirect_to(LessonResource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lesson_resource as @lesson_resource" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonResource.any_instance.stub(:save).and_return(false)
        post :create, {:lesson_resource => {}}, valid_session
        assigns(:lesson_resource).should be_a_new(LessonResource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LessonResource.any_instance.stub(:save).and_return(false)
        post :create, {:lesson_resource => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lesson_resource" do
        lesson_resource = LessonResource.create! valid_attributes
        # Assuming there are no other lesson_resources in the database, this
        # specifies that the LessonResource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LessonResource.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lesson_resource.to_param, :lesson_resource => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lesson_resource as @lesson_resource" do
        lesson_resource = LessonResource.create! valid_attributes
        put :update, {:id => lesson_resource.to_param, :lesson_resource => valid_attributes}, valid_session
        assigns(:lesson_resource).should eq(lesson_resource)
      end

      it "redirects to the lesson_resource" do
        lesson_resource = LessonResource.create! valid_attributes
        put :update, {:id => lesson_resource.to_param, :lesson_resource => valid_attributes}, valid_session
        response.should redirect_to(lesson_resource)
      end
    end

    describe "with invalid params" do
      it "assigns the lesson_resource as @lesson_resource" do
        lesson_resource = LessonResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => lesson_resource.to_param, :lesson_resource => {}}, valid_session
        assigns(:lesson_resource).should eq(lesson_resource)
      end

      it "re-renders the 'edit' template" do
        lesson_resource = LessonResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LessonResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => lesson_resource.to_param, :lesson_resource => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lesson_resource" do
      lesson_resource = LessonResource.create! valid_attributes
      expect {
        delete :destroy, {:id => lesson_resource.to_param}, valid_session
      }.to change(LessonResource, :count).by(-1)
    end

    it "redirects to the lesson_resources list" do
      lesson_resource = LessonResource.create! valid_attributes
      delete :destroy, {:id => lesson_resource.to_param}, valid_session
      response.should redirect_to(lesson_resources_url)
    end
  end

end
