require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LessonplansController do

  # This should return the minimal set of attributes required to create a valid
  # Lessonplan. As you add validations to Lessonplan, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LessonplansController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all lessonplans as @lessonplans" do
      lessonplan = Lessonplan.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lessonplans).should eq([lessonplan])
    end
  end

  describe "GET show" do
    it "assigns the requested lessonplan as @lessonplan" do
      lessonplan = Lessonplan.create! valid_attributes
      get :show, {:id => lessonplan.to_param}, valid_session
      assigns(:lessonplan).should eq(lessonplan)
    end
  end

  describe "GET new" do
    it "assigns a new lessonplan as @lessonplan" do
      get :new, {}, valid_session
      assigns(:lessonplan).should be_a_new(Lessonplan)
    end
  end

  describe "GET edit" do
    it "assigns the requested lessonplan as @lessonplan" do
      lessonplan = Lessonplan.create! valid_attributes
      get :edit, {:id => lessonplan.to_param}, valid_session
      assigns(:lessonplan).should eq(lessonplan)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lessonplan" do
        expect {
          post :create, {:lessonplan => valid_attributes}, valid_session
        }.to change(Lessonplan, :count).by(1)
      end

      it "assigns a newly created lessonplan as @lessonplan" do
        post :create, {:lessonplan => valid_attributes}, valid_session
        assigns(:lessonplan).should be_a(Lessonplan)
        assigns(:lessonplan).should be_persisted
      end

      it "redirects to the created lessonplan" do
        post :create, {:lessonplan => valid_attributes}, valid_session
        response.should redirect_to(Lessonplan.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lessonplan as @lessonplan" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lessonplan.any_instance.stub(:save).and_return(false)
        post :create, {:lessonplan => {}}, valid_session
        assigns(:lessonplan).should be_a_new(Lessonplan)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lessonplan.any_instance.stub(:save).and_return(false)
        post :create, {:lessonplan => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lessonplan" do
        lessonplan = Lessonplan.create! valid_attributes
        # Assuming there are no other lessonplans in the database, this
        # specifies that the Lessonplan created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lessonplan.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => lessonplan.to_param, :lessonplan => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested lessonplan as @lessonplan" do
        lessonplan = Lessonplan.create! valid_attributes
        put :update, {:id => lessonplan.to_param, :lessonplan => valid_attributes}, valid_session
        assigns(:lessonplan).should eq(lessonplan)
      end

      it "redirects to the lessonplan" do
        lessonplan = Lessonplan.create! valid_attributes
        put :update, {:id => lessonplan.to_param, :lessonplan => valid_attributes}, valid_session
        response.should redirect_to(lessonplan)
      end
    end

    describe "with invalid params" do
      it "assigns the lessonplan as @lessonplan" do
        lessonplan = Lessonplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lessonplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => lessonplan.to_param, :lessonplan => {}}, valid_session
        assigns(:lessonplan).should eq(lessonplan)
      end

      it "re-renders the 'edit' template" do
        lessonplan = Lessonplan.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lessonplan.any_instance.stub(:save).and_return(false)
        put :update, {:id => lessonplan.to_param, :lessonplan => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lessonplan" do
      lessonplan = Lessonplan.create! valid_attributes
      expect {
        delete :destroy, {:id => lessonplan.to_param}, valid_session
      }.to change(Lessonplan, :count).by(-1)
    end

    it "redirects to the lessonplans list" do
      lessonplan = Lessonplan.create! valid_attributes
      delete :destroy, {:id => lessonplan.to_param}, valid_session
      response.should redirect_to(lessonplans_url)
    end
  end

end
