require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RcategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # Rcategory. As you add validations to Rcategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RcategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all rcategories as @rcategories" do
      rcategory = Rcategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:rcategories).should eq([rcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested rcategory as @rcategory" do
      rcategory = Rcategory.create! valid_attributes
      get :show, {:id => rcategory.to_param}, valid_session
      assigns(:rcategory).should eq(rcategory)
    end
  end

  describe "GET new" do
    it "assigns a new rcategory as @rcategory" do
      get :new, {}, valid_session
      assigns(:rcategory).should be_a_new(Rcategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested rcategory as @rcategory" do
      rcategory = Rcategory.create! valid_attributes
      get :edit, {:id => rcategory.to_param}, valid_session
      assigns(:rcategory).should eq(rcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rcategory" do
        expect {
          post :create, {:rcategory => valid_attributes}, valid_session
        }.to change(Rcategory, :count).by(1)
      end

      it "assigns a newly created rcategory as @rcategory" do
        post :create, {:rcategory => valid_attributes}, valid_session
        assigns(:rcategory).should be_a(Rcategory)
        assigns(:rcategory).should be_persisted
      end

      it "redirects to the created rcategory" do
        post :create, {:rcategory => valid_attributes}, valid_session
        response.should redirect_to(Rcategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rcategory as @rcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rcategory.any_instance.stub(:save).and_return(false)
        post :create, {:rcategory => {}}, valid_session
        assigns(:rcategory).should be_a_new(Rcategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Rcategory.any_instance.stub(:save).and_return(false)
        post :create, {:rcategory => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested rcategory" do
        rcategory = Rcategory.create! valid_attributes
        # Assuming there are no other rcategories in the database, this
        # specifies that the Rcategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Rcategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => rcategory.to_param, :rcategory => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested rcategory as @rcategory" do
        rcategory = Rcategory.create! valid_attributes
        put :update, {:id => rcategory.to_param, :rcategory => valid_attributes}, valid_session
        assigns(:rcategory).should eq(rcategory)
      end

      it "redirects to the rcategory" do
        rcategory = Rcategory.create! valid_attributes
        put :update, {:id => rcategory.to_param, :rcategory => valid_attributes}, valid_session
        response.should redirect_to(rcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the rcategory as @rcategory" do
        rcategory = Rcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => rcategory.to_param, :rcategory => {}}, valid_session
        assigns(:rcategory).should eq(rcategory)
      end

      it "re-renders the 'edit' template" do
        rcategory = Rcategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Rcategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => rcategory.to_param, :rcategory => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rcategory" do
      rcategory = Rcategory.create! valid_attributes
      expect {
        delete :destroy, {:id => rcategory.to_param}, valid_session
      }.to change(Rcategory, :count).by(-1)
    end

    it "redirects to the rcategories list" do
      rcategory = Rcategory.create! valid_attributes
      delete :destroy, {:id => rcategory.to_param}, valid_session
      response.should redirect_to(rcategories_url)
    end
  end

end
