require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SelectSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # SelectSkill. As you add validations to SelectSkill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SelectSkillsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all select_skills as @select_skills" do
      select_skill = SelectSkill.create! valid_attributes
      get :index, {}, valid_session
      assigns(:select_skills).should eq([select_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested select_skill as @select_skill" do
      select_skill = SelectSkill.create! valid_attributes
      get :show, {:id => select_skill.to_param}, valid_session
      assigns(:select_skill).should eq(select_skill)
    end
  end

  describe "GET new" do
    it "assigns a new select_skill as @select_skill" do
      get :new, {}, valid_session
      assigns(:select_skill).should be_a_new(SelectSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested select_skill as @select_skill" do
      select_skill = SelectSkill.create! valid_attributes
      get :edit, {:id => select_skill.to_param}, valid_session
      assigns(:select_skill).should eq(select_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SelectSkill" do
        expect {
          post :create, {:select_skill => valid_attributes}, valid_session
        }.to change(SelectSkill, :count).by(1)
      end

      it "assigns a newly created select_skill as @select_skill" do
        post :create, {:select_skill => valid_attributes}, valid_session
        assigns(:select_skill).should be_a(SelectSkill)
        assigns(:select_skill).should be_persisted
      end

      it "redirects to the created select_skill" do
        post :create, {:select_skill => valid_attributes}, valid_session
        response.should redirect_to(SelectSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved select_skill as @select_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectSkill.any_instance.stub(:save).and_return(false)
        post :create, {:select_skill => {}}, valid_session
        assigns(:select_skill).should be_a_new(SelectSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SelectSkill.any_instance.stub(:save).and_return(false)
        post :create, {:select_skill => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested select_skill" do
        select_skill = SelectSkill.create! valid_attributes
        # Assuming there are no other select_skills in the database, this
        # specifies that the SelectSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SelectSkill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => select_skill.to_param, :select_skill => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested select_skill as @select_skill" do
        select_skill = SelectSkill.create! valid_attributes
        put :update, {:id => select_skill.to_param, :select_skill => valid_attributes}, valid_session
        assigns(:select_skill).should eq(select_skill)
      end

      it "redirects to the select_skill" do
        select_skill = SelectSkill.create! valid_attributes
        put :update, {:id => select_skill.to_param, :select_skill => valid_attributes}, valid_session
        response.should redirect_to(select_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the select_skill as @select_skill" do
        select_skill = SelectSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => select_skill.to_param, :select_skill => {}}, valid_session
        assigns(:select_skill).should eq(select_skill)
      end

      it "re-renders the 'edit' template" do
        select_skill = SelectSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SelectSkill.any_instance.stub(:save).and_return(false)
        put :update, {:id => select_skill.to_param, :select_skill => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested select_skill" do
      select_skill = SelectSkill.create! valid_attributes
      expect {
        delete :destroy, {:id => select_skill.to_param}, valid_session
      }.to change(SelectSkill, :count).by(-1)
    end

    it "redirects to the select_skills list" do
      select_skill = SelectSkill.create! valid_attributes
      delete :destroy, {:id => select_skill.to_param}, valid_session
      response.should redirect_to(select_skills_url)
    end
  end

end
