require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe XquestionsController do

  # This should return the minimal set of attributes required to create a valid
  # Xquestion. As you add validations to Xquestion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # XquestionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all xquestions as @xquestions" do
      xquestion = Xquestion.create! valid_attributes
      get :index, {}, valid_session
      assigns(:xquestions).should eq([xquestion])
    end
  end

  describe "GET show" do
    it "assigns the requested xquestion as @xquestion" do
      xquestion = Xquestion.create! valid_attributes
      get :show, {:id => xquestion.to_param}, valid_session
      assigns(:xquestion).should eq(xquestion)
    end
  end

  describe "GET new" do
    it "assigns a new xquestion as @xquestion" do
      get :new, {}, valid_session
      assigns(:xquestion).should be_a_new(Xquestion)
    end
  end

  describe "GET edit" do
    it "assigns the requested xquestion as @xquestion" do
      xquestion = Xquestion.create! valid_attributes
      get :edit, {:id => xquestion.to_param}, valid_session
      assigns(:xquestion).should eq(xquestion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Xquestion" do
        expect {
          post :create, {:xquestion => valid_attributes}, valid_session
        }.to change(Xquestion, :count).by(1)
      end

      it "assigns a newly created xquestion as @xquestion" do
        post :create, {:xquestion => valid_attributes}, valid_session
        assigns(:xquestion).should be_a(Xquestion)
        assigns(:xquestion).should be_persisted
      end

      it "redirects to the created xquestion" do
        post :create, {:xquestion => valid_attributes}, valid_session
        response.should redirect_to(Xquestion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved xquestion as @xquestion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Xquestion.any_instance.stub(:save).and_return(false)
        post :create, {:xquestion => {}}, valid_session
        assigns(:xquestion).should be_a_new(Xquestion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Xquestion.any_instance.stub(:save).and_return(false)
        post :create, {:xquestion => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested xquestion" do
        xquestion = Xquestion.create! valid_attributes
        # Assuming there are no other xquestions in the database, this
        # specifies that the Xquestion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Xquestion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => xquestion.to_param, :xquestion => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested xquestion as @xquestion" do
        xquestion = Xquestion.create! valid_attributes
        put :update, {:id => xquestion.to_param, :xquestion => valid_attributes}, valid_session
        assigns(:xquestion).should eq(xquestion)
      end

      it "redirects to the xquestion" do
        xquestion = Xquestion.create! valid_attributes
        put :update, {:id => xquestion.to_param, :xquestion => valid_attributes}, valid_session
        response.should redirect_to(xquestion)
      end
    end

    describe "with invalid params" do
      it "assigns the xquestion as @xquestion" do
        xquestion = Xquestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Xquestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => xquestion.to_param, :xquestion => {}}, valid_session
        assigns(:xquestion).should eq(xquestion)
      end

      it "re-renders the 'edit' template" do
        xquestion = Xquestion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Xquestion.any_instance.stub(:save).and_return(false)
        put :update, {:id => xquestion.to_param, :xquestion => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested xquestion" do
      xquestion = Xquestion.create! valid_attributes
      expect {
        delete :destroy, {:id => xquestion.to_param}, valid_session
      }.to change(Xquestion, :count).by(-1)
    end

    it "redirects to the xquestions list" do
      xquestion = Xquestion.create! valid_attributes
      delete :destroy, {:id => xquestion.to_param}, valid_session
      response.should redirect_to(xquestions_url)
    end
  end

end
